stages:
  - build

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 100

default:
  cache: {}

android-build-release:
  stage: build
  image: paritytech/parity-signer
  tags:
    - linux-docker
  only:
    - master
    - /^[0-9]+$/
  artifacts:
    paths:
      - signer-app-release-signed.apk
  script: |
    cat "$KEYSTORE_DATA" | base64 -d > /tmp/gitlab-ci.keystore
    wc /tmp/gitlab-ci.keystore
    ./scripts/build-release.sh /tmp/gitlab-ci.keystore "$KEYSTORE_ALIAS" "$KEYSTORE_PASS"
